import functions
json_file = functions.load_json_file()
# functions.load_json_file()
# functions.save_titles_by_category(functions.load_json_file(),)
# functions.save_titles_by_category(json_file)
# functions.universities_by_state(json_file)
# functions.university_data_to_csv(json_file)
# functions.adoptions_to_csv(json_file)
# functions.contacts_to_csv(json_file)
# functions.messages_to_csv(json_file)
functions.books_to_csv(json_file)